import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import { Assistant } from '@next/font/google';
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import Section from '@/components/Section';
import Footer from '@/components/Footer';
import HomeContact from '@/components/HomeContact';
// states
import { useMobileContext } from '@/context/mobile';

export default function Home() {
  // states
  const [isMobile, serIsMobile] = useMobileContext();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <header className="header" id="top">
          <Header />
        </header>
        <section>
          <Hero />
        </section>
        <section>
          <Section
            flipped={true}
            img="https://images.pexels.com/photos/618158/pexels-photo-618158.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
          />
        </section>
        <section>
          <HomeContact />
        </section>
        <section>
          <Section img="https://images.pexels.com/photos/7875996/pexels-photo-7875996.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" />
        </section>
        <footer>
          <Footer />
        </footer>
      </main>
    </>
  );
}
